### ISSUE TITLE
Some repo names don't work

### ISSUE THREAD

**Issue by papajohn** [data-8/nbinteract#4]
I tried to use `data-8.github.io` as the `repo` argument, but interact hung with the attached error. I think maybe it's because of punctuation? The same content in `data8assets` loaded fine.

<img width="985" alt="screen shot 2017-01-17 at 3 17 10 pm" src="https://cloud.githubusercontent.com/assets/320145/22044576/3ed629be-dcca-11e6-99c7-1dd9ed47ed3d.png">

**Comment by tonyyanga** [comment]
Before pull request #14 is merged, nbinteract can only pull from "gh_pages" branch of the specified repo, which seems to cause the error. Issues seems fixed with the new pull request, when tested with 

`?repo=data-8.github.io&branch=master&path=index.html`

Nevertheless, the large size of data-8.github.io repo causes the pull procedure to take longer time. Future optimization may be needed. @SaladRaider

**Comment by SaladRaider** [comment]
This is fixed now.
